image: fedora/rawhide
packages:
  - java-latest-openjdk-devel.x86_64
  - java-latest-openjdk-jmods.x86_64
sources:
  - https://git.sr.ht/~_masven/aws-manager
tasks:
  - setup: |
        cd aws-manager
  - test: |
        cd aws-manager
        ./gradlew test
  - preparemodule: |
        cd aws-manager
        ./gradlew prepareMergedJarsDir
        ./gradlew createMergedModule
        ./gradlew createDelegatingModules
        ./gradlew prepareModulesDir
  - build: |
        cd aws-manager
        ./gradlew :gui:jlinkZip
artifacts:
  - aws-manager/gui/build/image.zip
