# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install java 15"
          command: (New-Object System.Net.WebClient).DownloadFile("https://download.java.net/java/early_access/jdk15/31/GPL/openjdk-15-ea+31_windows-x64_bin.zip","openjdk.zip")
      - run:
          name: "uncompress"
          command: Expand-Archive -LiteralPath openjdk.zip -DestinationPath openjdk
      - run:
          name: "echo"
          command: dir
      - run: ./gradlew dependencies "-Dorg.gradle.java.home=openjdk/jdk-15" "--no-daemon"
      - save_cache:
          paths:
            - ~/.gradle
            - openjdk
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test "-Dorg.gradle.java.home=openjdk/jdk-15" "--no-daemon"
      - run: ./gradlew :gui:jpackageImage "-Dorg.gradle.java.home=openjdk/jdk-15" "--no-daemon"
      - store_artifacts:
          path: gui/build/image
      - store_artifacts:
          path: gui/build/jpackage

