# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            - openjdk-15
      - run:
          name: "Install java 15"
          command: (New-Object System.Net.WebClient).DownloadFile("https://download.java.net/java/early_access/jdk15/31/GPL/openjdk-15-ea+31_windows-x64_bin.zip","openjdk.zip")
      - run:
          name: "uncompress"
          command: Expand-Archive -LiteralPath openjdk.zip -DestinationPath openjdk

      - run: gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
            - openjdk
          key:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - openjdk-15

      # run tests!
      - run: gradlew test
      - run: gradlew jpackage

