# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install java 15"
          command: |
              if (-Not( Test-Path openjdk/jdk-14.0.2)){
                         (New-Object System.Net.WebClient).DownloadFile("https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_windows-x64_bin.zip","openjdk.zip")
                }

      - run:
          name: "uncompress"
          command: |
              if (Test-Path openjdk.zip){
                Expand-Archive -Force -LiteralPath openjdk.zip -DestinationPath openjdk
              }
      - run:
          name: "echo"
          command: dir
      - run: ./gradlew dependencies "-Dorg.gradle.java.home=openjdk/jdk-14.0.2" "--no-daemon"
      - save_cache:
          paths:
            - ~/.gradle
            - openjdk/jdk-14.0.2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test "-Dorg.gradle.java.home=openjdk/jdk-14.0.2" "--no-daemon"
      - run: ./gradlew :gui:jlinkZip "-Dorg.gradle.java.home=openjdk/jdk-14.0.2" "--no-daemon"
      - store_artifacts:
          path: gui/build/image.zip

