# .github/workflows/build.yml
name: Build new binary on every push
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jlinkZip
      - uses: actions/upload-artifact@v2
        with:
          name: aws-manager-${{ matrix.os}}
          path: gui/build/image.zip